apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: default
  labels:
    app: javafrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javafrontend
  template:
    metadata:
      labels:
        app: javafrontend
    spec:
      containers:
        - name: devops
          image: frontendtestjava.azurecr.io/srinivasareddy4218/jwt-authentication:20
           imagePullPolicy: Always
          ports:
            - containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: javafrontend
  ports:
    - protocol: TCP
      port: 8092
      nodePort: 32002
